// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";

/**
 * @title OKBOND Vault V7 FINAL
  * @notice Holds and distributes tokens across ecosystem modules
   * @dev No owner, only timelock governance
    */
    contract OKBOND_Vault_V7 {
        using SafeERC20 for IERC20;

            // =========================
                // CORE
                    // =========================
                        IERC20 public immutable okbond;
                            address public timelock;
                                address public pendingTimelock;

                                    uint256 public immutable deploymentTime;

                                        modifier onlyTimelock() {
                                                require(msg.sender == timelock, "Not timelock");
                                                        _;
                                                            }

                                                                // =========================
                                                                    // TOKENOMICS (FIXED 10M)
                                                                        // =========================
                                                                            uint256 public constant STAKING_POOL = 2_800_000 * 1e18;   // 28%
                                                                                uint256 public constant ECOSYSTEM_POOL = 2_000_000 * 1e18; // 20%
                                                                                    uint256 public constant LIQUIDITY_POOL = 2_000_000 * 1e18; // 20%
                                                                                        uint256 public constant DEV_POOL = 1_200_000 * 1e18;       // 12%
                                                                                            uint256 public constant ICO_POOL = 1_000_000 * 1e18;       // 10%
                                                                                                uint256 public constant TEAM_POOL = 1_000_000 * 1e18;      // 10%

                                                                                                    // =========================
                                                                                                        // SUB-LOCKS (Liquidity Split)
                                                                                                            // =========================
                                                                                                                uint256 public constant FAMILY_LOCK = 1_000_000 * 1e18; // 10% (from liquidity)
                                                                                                                    uint256 public constant LP_LOCK = 1_000_000 * 1e18;     // 10% (from liquidity)

                                                                                                                        // =========================
                                                                                                                            // TIME RULES
                                                                                                                                // =========================
                                                                                                                                    uint256 public constant TEAM_CLIFF = 365 days;
                                                                                                                                        uint256 public constant TEAM_VESTING = 2 * 365 days;

                                                                                                                                            uint256 public constant FAMILY_LOCK_DURATION = 10 * 365 days;
                                                                                                                                                uint256 public constant LP_LOCK_DURATION = 8 * 365 days;

                                                                                                                                                    // =========================
                                                                                                                                                        // STATE TRACKING
                                                                                                                                                            // =========================
                                                                                                                                                                uint256 public stakingAllocated;
                                                                                                                                                                    uint256 public ecosystemAllocated;
                                                                                                                                                                        uint256 public devAllocated;
                                                                                                                                                                            uint256 public icoAllocated;
                                                                                                                                                                                uint256 public teamClaimed;

                                                                                                                                                                                    bool public familyClaimed;
                                                                                                                                                                                        bool public lpUnlocked;

                                                                                                                                                                                            // =========================
                                                                                                                                                                                                // EVENTS
                                                                                                                                                                                                    // =========================
                                                                                                                                                                                                        event TimelockProposed(address newTimelock);
                                                                                                                                                                                                            event TimelockUpdated(address newTimelock);

                                                                                                                                                                                                                event StakingFunded(address indexed target, uint256 amount);
                                                                                                                                                                                                                    event EcosystemFunded(address indexed target, uint256 amount);
                                                                                                                                                                                                                        event DevFunded(address indexed target, uint256 amount);
                                                                                                                                                                                                                            event ICOFunded(address indexed target, uint256 amount);

                                                                                                                                                                                                                                event TeamReleased(uint256 amount);
                                                                                                                                                                                                                                    event FamilyUnlocked(uint256 amount);
                                                                                                                                                                                                                                        event LiquidityUnlocked(uint256 amount);

                                                                                                                                                                                                                                            // =========================
                                                                                                                                                                                                                                                // CONSTRUCTOR
                                                                                                                                                                                                                                                    // =========================
                                                                                                                                                                                                                                                        constructor(address _token, address _timelock) {
                                                                                                                                                                                                                                                                require(_token != address(0), "Invalid token");
                                                                                                                                                                                                                                                                        require(_timelock != address(0), "Invalid timelock");

                                                                                                                                                                                                                                                                                okbond = IERC20(_token);
                                                                                                                                                                                                                                                                                        timelock = _timelock;
                                                                                                                                                                                                                                                                                                deploymentTime = block.timestamp;
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                        // =========================
                                                                                                                                                                                                                                                                                                            // TIMELOCK MANAGEMENT
                                                                                                                                                                                                                                                                                                                // =========================
                                                                                                                                                                                                                                                                                                                    function proposeTimelock(address newTimelock) external onlyTimelock {
                                                                                                                                                                                                                                                                                                                            require(newTimelock != address(0), "Invalid");
                                                                                                                                                                                                                                                                                                                                    pendingTimelock = newTimelock;
                                                                                                                                                                                                                                                                                                                                            emit TimelockProposed(newTimelock);
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                    function acceptTimelock() external {
                                                                                                                                                                                                                                                                                                                                                            require(msg.sender == pendingTimelock, "Not pending");
                                                                                                                                                                                                                                                                                                                                                                    timelock = pendingTimelock;
                                                                                                                                                                                                                                                                                                                                                                            pendingTimelock = address(0);
                                                                                                                                                                                                                                                                                                                                                                                    emit TimelockUpdated(timelock);
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                            // =========================
                                                                                                                                                                                                                                                                                                                                                                                                // FUNDING MODULES
                                                                                                                                                                                                                                                                                                                                                                                                    // =========================
                                                                                                                                                                                                                                                                                                                                                                                                        function fundStaking(address target, uint256 amount) external onlyTimelock {
                                                                                                                                                                                                                                                                                                                                                                                                                require(stakingAllocated + amount <= STAKING_POOL, "Exceeds staking");
                                                                                                                                                                                                                                                                                                                                                                                                                        stakingAllocated += amount;
                                                                                                                                                                                                                                                                                                                                                                                                                                okbond.safeTransfer(target, amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                        emit StakingFunded(target, amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                function fundEcosystem(address target, uint256 amount) external onlyTimelock {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        require(ecosystemAllocated + amount <= ECOSYSTEM_POOL, "Exceeds ecosystem");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ecosystemAllocated += amount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        okbond.safeTransfer(target, amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                emit EcosystemFunded(target, amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function fundDevelopment(address target, uint256 amount) external onlyTimelock {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                require(devAllocated + amount <= DEV_POOL, "Exceeds dev");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        devAllocated += amount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                okbond.safeTransfer(target, amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        emit DevFunded(target, amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function fundICO(address target, uint256 amount) external onlyTimelock {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        require(icoAllocated + amount <= ICO_POOL, "Exceeds ICO");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                icoAllocated += amount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        okbond.safeTransfer(target, amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                emit ICOFunded(target, amount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // TEAM VESTING
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function releaseTeam(address teamWallet) external onlyTimelock {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            require(block.timestamp >= deploymentTime + TEAM_CLIFF, "Cliff");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    uint256 elapsed = block.timestamp - (deploymentTime + TEAM_CLIFF);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (elapsed > TEAM_VESTING) elapsed = TEAM_VESTING;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    uint256 vested = (TEAM_POOL * elapsed) / TEAM_VESTING;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            uint256 claimable = vested - teamClaimed;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    require(claimable > 0, "Nothing");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            teamClaimed += claimable;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    okbond.safeTransfer(teamWallet, claimable);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            emit TeamReleased(claimable);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // FAMILY LOCK (10 YEARS)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function claimFamily(address wallet) external onlyTimelock {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        require(!familyClaimed, "Claimed");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                require(block.timestamp >= deploymentTime + FAMILY_LOCK_DURATION, "Locked");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        familyClaimed = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                okbond.safeTransfer(wallet, FAMILY_LOCK);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        emit FamilyUnlocked(FAMILY_LOCK);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // LIQUIDITY LOCK (8 YEARS)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function unlockLiquidity(address wallet) external onlyTimelock {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    require(!lpUnlocked, "Unlocked");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            require(block.timestamp >= deploymentTime + LP_LOCK_DURATION, "Locked");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    lpUnlocked = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            okbond.safeTransfer(wallet, LP_LOCK);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    emit LiquidityUnlocked(LP_LOCK);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // VIEW
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // =========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function vaultBalance() external view returns (uint256) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return okbond.balanceOf(address(this));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }